name: "smoketest"
on:
  push:
  pull_request:
jobs:
  smoketest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [python37, python38]
        plone: [plone523]
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: datakurre
    - run: nix-shell setup.nix --argstr plone ${{ matrix.plone }} --argstr python ${{ matrix.python }} -A shell --run "buildout"
    - run: nix-build zconfig/instance.nix -o zope.conf
    - run: mkdir -p var/filestorage
    - run: nix-shell setup.nix --argstr plone ${{ matrix.plone }} --argstr python ${{ matrix.python }} -A shell --run "bin/plonectl instance -C zope.conf run zconfig/plonesite.py"
